[package]
name = "aoc-solutions"
version = "0.1.0"
edition = "2024"

[dependencies]
md-5 = "0.10"
itertools = "0.14"
json = "0.12"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib", "rlib"]